name: scanai_app
description: A application for real-time object detection with video streaming.
version: 1.0.0+2013


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  
  permission_handler: ^12.0.1
  
  # Network
  http: ^1.6.0
  web_socket_channel: ^3.0.3
  
  # State Management
  provider: ^6.1.1
  
  # Utility
  path_provider: ^2.1.2
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # Image Processing
  image: ^4.1.3

  # Threading & Performance

  synchronized: ^3.1.0+1
  wakelock_plus: ^1.2.8
  battery_plus: ^7.0.0
  
  # UI
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.3.0
  flutter_secure_storage: ^10.0.0
  
  # Gallery
  image_gallery_saver_plus: ^4.0.1
  google_fonts: ^6.3.3
  
  # iOS Inter-App Communication
  url_launcher: ^6.2.5
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.jpg"
  min_sdk_android: 21
